on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "RELEASE=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - uses: actions/github-script@v4
      id: set-result
      with:
        script: |
          var response ="Hello!";
          return response
        result-encoding: string
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}" 
