---
name: publish
on:
  push:
    branches-ignore:
    - '*'
    tags:
    - 'v[0-9]*'
jobs:
  publish-helm-charts:
    env:
      IMAGE_NAME: silly-helm-repo
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${GITHUB_REF#refs/tags/}
          echo "RELEASE=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Auto-merge
        uses: actions/github-script@v4
        id: junk
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var release = await github.repos.getReleaseByTag({
              owner: context.repo.owner ,
              repo: context.repo.repo,
              tag: process.env.RELEASE,
            })

            return release.id
          
      - run: |
          echo ${{ steps.junk.outputs.result }}