---
name: publish
on:
  push:
    branches-ignore:
    - '*'
    tags:
    - 'v[0-9]*'
jobs:
  publish-helm-charts:
    env:
      IMAGE_NAME: silly-helm-repo
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${GITHUB_REF#refs/tags/}
          echo ${GITHUB_REF}
      - name: Auto-merge
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const GITHUB_REF = process.env;
            release_id = octokit.rest.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: ${GITHUB_REF},
            });
            return release_id.id;

#            octokit.rest.repos.uploadReleaseAsset({
#            owner: context.repo.owner,
#            repo: context.repo.repo,
#            release_id,
#            data,
#            })
#    - name: Checkout Source
#      uses: actions/checkout@v2
#      with:
#        fetch-depth: 0

#    - name: Checkout gh-pages
#      uses: actions/checkout@v2
#      with:
#        ref: gh-pages
#        path: gh-pages

#    - name: Configure Helm
#      uses: azure/setup-helm@v1
#      with:
#        version: latest

#    - name: Package Helm Chart
#      run: |
#        helm dep up helm/
#        helm package helm/
#        mv ${{ env.IMAGE_NAME }}-*.tgz gh-pages
#        helm repo index --url https://redhat-cop.github.io/${{ env.IMAGE_NAME }} gh-pages

#    - name: Push Changes to GH Pages
#      run: |
#        cd gh-pages
#        git config user.name "$GITHUB_ACTOR"
#        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
#        git add .
#        git commit -m "Updating Helm Chart Repository"
#        git push
