---
name: publish
on:
  push:
    branches-ignore:
    - '*'
    tags:
    - 'v[0-9]*'
jobs:
  publish-helm-charts:
    env:
      IMAGE_NAME: silly-helm-repo
      RELEASE: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${GITHUB_REF#refs/tags/}
          echo ${GITHUB_REF}
      - name: Auto-merge
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const RELEASE = process.env;
            console.log('${RELEASE}')
