kind: Pod
apiVersion: v1
metadata:
  name: "{{ .Values.app_name }}-app"
  labels:
    app: "{{ .Values.app_name }}"
spec:
  containers:
    - name: "{{ .Values.app_name }}-app"
      image: hashicorp/http-echo
      args:
        - "-text={{ .Values.app_name }}"

---

kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.app_name }}-service"
spec:
  selector:
    app: "{{ .Values.app_name }}"
  ports:
    - port: 5678 # Default port for image
