{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ .Values.app_name }}-service"
spec:
  port:
    targetPort: 5678
  to:
    kind: Service
    name: "{{ .Values.app_name }}-service"
    weight: 100
  wildcardPolicy: None
{{- end -}}
